services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./public/:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - nodejs

  nodejs:
    image: node:18-alpine # ใช้ Node.js Image โดยตรง
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    command: sh -c "npm install && node server.js"
